services:
  worker:
    # container_name: credora-worker
    image: credora-backend:v1.00
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app-network
    command: ./worker
    deploy:
      replicas: 3

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge