// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountWithMonnify = `-- name: CreateAccountWithMonnify :one
INSERT INTO accounts (
    user_id,
    account_number,
    account_type,
    monnify_customer_ref,
    virtual_account_bank
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, account_number, account_type, balance, currency, created_at, updated_at, virtual_account_bank, monnify_customer_ref
`

type CreateAccountWithMonnifyParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	AccountNumber      string      `json:"account_number"`
	AccountType        string      `json:"account_type"`
	MonnifyCustomerRef pgtype.Text `json:"monnify_customer_ref"`
	VirtualAccountBank pgtype.Text `json:"virtual_account_bank"`
}

func (q *Queries) CreateAccountWithMonnify(ctx context.Context, arg CreateAccountWithMonnifyParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccountWithMonnify,
		arg.UserID,
		arg.AccountNumber,
		arg.AccountType,
		arg.MonnifyCustomerRef,
		arg.VirtualAccountBank,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VirtualAccountBank,
		&i.MonnifyCustomerRef,
	)
	return i, err
}

const creditAccountBalance = `-- name: CreditAccountBalance :one
UPDATE accounts
SET balance = balance + $1
WHERE account_number = $2
RETURNING id, balance
`

type CreditAccountBalanceParams struct {
	Amount        pgtype.Numeric `json:"amount"`
	AccountNumber string         `json:"account_number"`
}

type CreditAccountBalanceRow struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) CreditAccountBalance(ctx context.Context, arg CreditAccountBalanceParams) (CreditAccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, creditAccountBalance, arg.Amount, arg.AccountNumber)
	var i CreditAccountBalanceRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const debitAccountBalance = `-- name: DebitAccountBalance :one
UPDATE accounts
SET balance = balance - $1
WHERE account_number = $2
RETURNING id, balance
`

type DebitAccountBalanceParams struct {
	Amount        pgtype.Numeric `json:"amount"`
	AccountNumber string         `json:"account_number"`
}

type DebitAccountBalanceRow struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) DebitAccountBalance(ctx context.Context, arg DebitAccountBalanceParams) (DebitAccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, debitAccountBalance, arg.Amount, arg.AccountNumber)
	var i DebitAccountBalanceRow
	err := row.Scan(&i.ID, &i.Balance)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, user_id, account_number, account_type, balance, currency, created_at, updated_at, virtual_account_bank, monnify_customer_ref
FROM accounts
WHERE account_number = $1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, accountNumber string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, accountNumber)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VirtualAccountBank,
		&i.MonnifyCustomerRef,
	)
	return i, err
}

const getUserByAccountNumber = `-- name: GetUserByAccountNumber :one
SELECT u.id, u.password, u.full_name, u.email, u.phone_number, a.account_number, a.balance, a.virtual_account_bank
FROM accounts a
JOIN users u ON a.user_id = u.id
WHERE a.account_number = $1
`

type GetUserByAccountNumberRow struct {
	ID                 uuid.UUID      `json:"id"`
	Password           string         `json:"password"`
	FullName           string         `json:"full_name"`
	Email              pgtype.Text    `json:"email"`
	PhoneNumber        string         `json:"phone_number"`
	AccountNumber      string         `json:"account_number"`
	Balance            pgtype.Numeric `json:"balance"`
	VirtualAccountBank pgtype.Text    `json:"virtual_account_bank"`
}

func (q *Queries) GetUserByAccountNumber(ctx context.Context, accountNumber string) (GetUserByAccountNumberRow, error) {
	row := q.db.QueryRow(ctx, getUserByAccountNumber, accountNumber)
	var i GetUserByAccountNumberRow
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.AccountNumber,
		&i.Balance,
		&i.VirtualAccountBank,
	)
	return i, err
}
