// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: device_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceToken = `-- name: CreateDeviceToken :one
INSERT INTO device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, platform, created_at
`

type CreateDeviceTokenParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	Token    string      `json:"token"`
	Platform pgtype.Text `json:"platform"`
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, createDeviceToken, arg.UserID, arg.Token, arg.Platform)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE id = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, id)
	return err
}

const deleteDeviceTokensByUserID = `-- name: DeleteDeviceTokensByUserID :exec
DELETE FROM device_tokens WHERE user_id = $1
`

func (q *Queries) DeleteDeviceTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokensByUserID, userID)
	return err
}

const getDeviceTokensByUserID = `-- name: GetDeviceTokensByUserID :many
SELECT id, user_id, token, platform, created_at FROM device_tokens WHERE user_id = $1
`

func (q *Queries) GetDeviceTokensByUserID(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceToken = `-- name: UpdateDeviceToken :one
UPDATE device_tokens
SET token = $1, platform = $2
WHERE id = $3
RETURNING id, user_id, token, platform, created_at
`

type UpdateDeviceTokenParams struct {
	Token    string      `json:"token"`
	Platform pgtype.Text `json:"platform"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdateDeviceToken(ctx context.Context, arg UpdateDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, updateDeviceToken, arg.Token, arg.Platform, arg.ID)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
	)
	return i, err
}
