// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idempotency.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const checkIdempotency = `-- name: CheckIdempotency :one
SELECT EXISTS (
    SELECT 1 FROM idempotency_keys
    WHERE idem_key = $1
) AS exists
`

func (q *Queries) CheckIdempotency(ctx context.Context, idemKey string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIdempotency, idemKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE idem_key = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, idemKey string) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, idemKey)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT idem_key, operation_type, payload, created_at, processed_at, status
FROM idempotency_keys
WHERE idem_key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, idemKey string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, idemKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.IdemKey,
		&i.OperationType,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.Status,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (idem_key, operation_type, payload, status)
VALUES ($1, $2, $3, $4)
`

type InsertIdempotencyKeyParams struct {
	IdemKey       string          `json:"idem_key"`
	OperationType string          `json:"operation_type"`
	Payload       json.RawMessage `json:"payload"`
	Status        string          `json:"status"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.IdemKey,
		arg.OperationType,
		arg.Payload,
		arg.Status,
	)
	return err
}

const saveIdempotencyFailure = `-- name: SaveIdempotencyFailure :exec
UPDATE idempotency_keys
SET status = 'FAILED',
    payload = $2,
    updated_at = NOW()
WHERE idem_key = $1
`

type SaveIdempotencyFailureParams struct {
	IdemKey string          `json:"idem_key"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) SaveIdempotencyFailure(ctx context.Context, arg SaveIdempotencyFailureParams) error {
	_, err := q.db.Exec(ctx, saveIdempotencyFailure, arg.IdemKey, arg.Payload)
	return err
}

const saveIdempotencySuccess = `-- name: SaveIdempotencySuccess :exec
UPDATE idempotency_keys
SET status = 'SUCCESS',
    payload = $2,
    updated_at = NOW()
WHERE idem_key = $1
`

type SaveIdempotencySuccessParams struct {
	IdemKey string          `json:"idem_key"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) SaveIdempotencySuccess(ctx context.Context, arg SaveIdempotencySuccessParams) error {
	_, err := q.db.Exec(ctx, saveIdempotencySuccess, arg.IdemKey, arg.Payload)
	return err
}

const updateIdempotencyStatus = `-- name: UpdateIdempotencyStatus :exec
UPDATE idempotency_keys
SET status = $2,
    updated_at = NOW()
WHERE idem_key = $1
`

type UpdateIdempotencyStatusParams struct {
	IdemKey string `json:"idem_key"`
	Status  string `json:"status"`
}

func (q *Queries) UpdateIdempotencyStatus(ctx context.Context, arg UpdateIdempotencyStatusParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyStatus, arg.IdemKey, arg.Status)
	return err
}

const upsertIdempotencyKey = `-- name: UpsertIdempotencyKey :exec

INSERT INTO idempotency_keys (idem_key, operation_type, payload, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (idem_key)
DO UPDATE SET
    operation_type = EXCLUDED.operation_type,
    payload        = EXCLUDED.payload,
    status         = EXCLUDED.status
WHERE 
    idempotency_keys.operation_type IS DISTINCT FROM EXCLUDED.operation_type
 OR idempotency_keys.payload        IS DISTINCT FROM EXCLUDED.payload
 OR idempotency_keys.status         IS DISTINCT FROM EXCLUDED.status
`

type UpsertIdempotencyKeyParams struct {
	IdemKey       string          `json:"idem_key"`
	OperationType string          `json:"operation_type"`
	Payload       json.RawMessage `json:"payload"`
	Status        string          `json:"status"`
}

// -- name: UpsertIdempotencyKey :exec
// INSERT INTO idempotency_keys (idem_key, operation_type, payload, status)
// VALUES ($1, $2, $3, $4)
// ON CONFLICT (idem_key) DO NOTHING;
func (q *Queries) UpsertIdempotencyKey(ctx context.Context, arg UpsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, upsertIdempotencyKey,
		arg.IdemKey,
		arg.OperationType,
		arg.Payload,
		arg.Status,
	)
	return err
}
