// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                 uuid.UUID        `json:"id"`
	UserID             uuid.UUID        `json:"user_id"`
	AccountNumber      string           `json:"account_number"`
	AccountType        string           `json:"account_type"`
	Balance            pgtype.Numeric   `json:"balance"`
	Currency           string           `json:"currency"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	VirtualAccountBank pgtype.Text      `json:"virtual_account_bank"`
	MonnifyCustomerRef pgtype.Text      `json:"monnify_customer_ref"`
	Username           string           `json:"username"`
}

type DeviceToken struct {
	ID        int64            `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Token     string           `json:"token"`
	Platform  pgtype.Text      `json:"platform"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type IdempotencyKey struct {
	IdemKey       string             `json:"idem_key"`
	OperationType string             `json:"operation_type"`
	Payload       json.RawMessage    `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	Status        string             `json:"status"`
}

type PasswordReset struct {
	ID        int64            `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UsedAt    pgtype.Timestamp `json:"used_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Transaction struct {
	AccountID             pgtype.UUID        `json:"account_id"`
	Amount                pgtype.Numeric     `json:"amount"`
	Status                string             `json:"status"`
	Description           pgtype.Text        `json:"description"`
	Reference             pgtype.Text        `json:"reference"`
	Channel               pgtype.Text        `json:"channel"`
	Meta                  []byte             `json:"meta"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	Direction             pgtype.Text        `json:"direction"`
	CounterpartyAccountID pgtype.UUID        `json:"counterparty_account_id"`
	ID                    int64              `json:"id"`
}

type User struct {
	ID                 uuid.UUID        `json:"id"`
	FullName           string           `json:"full_name"`
	Email              string           `json:"email"`
	PhoneNumber        string           `json:"phone_number"`
	Password           string           `json:"password"`
	IsVerified         pgtype.Bool      `json:"is_verified"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Nin                string           `json:"nin"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	MonnifyCustomerRef pgtype.Text      `json:"monnify_customer_ref"`
}
