// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                 uuid.UUID        `json:"id"`
	UserID             pgtype.UUID      `json:"user_id"`
	AccountNumber      string           `json:"account_number"`
	AccountType        string           `json:"account_type"`
	Balance            pgtype.Numeric   `json:"balance"`
	Currency           string           `json:"currency"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	VirtualAccountBank pgtype.Text      `json:"virtual_account_bank"`
	MonnifyCustomerRef pgtype.Text      `json:"monnify_customer_ref"`
}

type Transaction struct {
	ID          uuid.UUID        `json:"id"`
	AccountID   pgtype.UUID      `json:"account_id"`
	Amount      pgtype.Numeric   `json:"amount"`
	Status      string           `json:"status"`
	Description pgtype.Text      `json:"description"`
	Reference   pgtype.Text      `json:"reference"`
	Channel     pgtype.Text      `json:"channel"`
	Meta        []byte           `json:"meta"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                 uuid.UUID        `json:"id"`
	FullName           string           `json:"full_name"`
	Email              pgtype.Text      `json:"email"`
	PhoneNumber        string           `json:"phone_number"`
	Password           string           `json:"password"`
	IsVerified         pgtype.Bool      `json:"is_verified"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Nin                string           `json:"nin"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	MonnifyCustomerRef pgtype.Text      `json:"monnify_customer_ref"`
}
