// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: password_resets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (user_id, token_hash, expires_at, used_at, created_at)
VALUES ($1, $2, $3, $4, COALESCE($5, NOW()))
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID        `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UsedAt    pgtype.Timestamp `json:"used_at"`
	Column5   interface{}      `json:"column_5"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.Column5,
	)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasswordReset = `-- name: DeletePasswordReset :exec
DELETE FROM password_resets
WHERE id = $1
`

func (q *Queries) DeletePasswordReset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePasswordReset, id)
	return err
}

const getActivePasswordReset = `-- name: GetActivePasswordReset :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM password_resets
WHERE user_id = $1
  AND used_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActivePasswordReset(ctx context.Context, userID uuid.UUID) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getActivePasswordReset, userID)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePasswordResetUsedAt = `-- name: UpdatePasswordResetUsedAt :exec
UPDATE password_resets
SET used_at = $2
WHERE id = $1
`

type UpdatePasswordResetUsedAtParams struct {
	ID     int64            `json:"id"`
	UsedAt pgtype.Timestamp `json:"used_at"`
}

func (q *Queries) UpdatePasswordResetUsedAt(ctx context.Context, arg UpdatePasswordResetUsedAtParams) error {
	_, err := q.db.Exec(ctx, updatePasswordResetUsedAt, arg.ID, arg.UsedAt)
	return err
}
