// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// -- name: UpdateUser :one
	// This query is commented out because it updates manually but I have associated trigger
	// that automatically updates the `updated_at` field on any update.
	// UPDATE users
	// SET name = $2, email = $3, updated_at = NOW()
	// WHERE id = $1
	// RETURNING *;
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
