// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordNewTransaction = `-- name: RecordNewTransaction :one
INSERT INTO transactions (
    account_id,
    counterparty_account_id,
    amount,
    direction,
    status,
    description,
    reference,
    channel,
    meta
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, account_id, amount, status, description, reference, channel, meta, created_at, direction, counterparty_account_id
`

type RecordNewTransactionParams struct {
	AccountID             pgtype.UUID    `json:"account_id"`
	CounterpartyAccountID pgtype.UUID    `json:"counterparty_account_id"`
	Amount                pgtype.Numeric `json:"amount"`
	Direction             pgtype.Text    `json:"direction"`
	Status                string         `json:"status"`
	Description           pgtype.Text    `json:"description"`
	Reference             pgtype.Text    `json:"reference"`
	Channel               pgtype.Text    `json:"channel"`
	Meta                  []byte         `json:"meta"`
}

func (q *Queries) RecordNewTransaction(ctx context.Context, arg RecordNewTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, recordNewTransaction,
		arg.AccountID,
		arg.CounterpartyAccountID,
		arg.Amount,
		arg.Direction,
		arg.Status,
		arg.Description,
		arg.Reference,
		arg.Channel,
		arg.Meta,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Status,
		&i.Description,
		&i.Reference,
		&i.Channel,
		&i.Meta,
		&i.CreatedAt,
		&i.Direction,
		&i.CounterpartyAccountID,
	)
	return i, err
}
