// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, full_name, phone_number, password, nin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, full_name, email, phone_number, password, is_verified, created_at, updated_at, nin, expires_at, monnify_customer_ref
`

type CreateUserParams struct {
	Email       string `json:"email"`
	FullName    string `json:"full_name"`
	PhoneNumber string `json:"phone_number"`
	Password    string `json:"password"`
	Nin         string `json:"nin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FullName,
		arg.PhoneNumber,
		arg.Password,
		arg.Nin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nin,
		&i.ExpiresAt,
		&i.MonnifyCustomerRef,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, phone_number, password, is_verified, created_at, updated_at, nin, expires_at, monnify_customer_ref FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nin,
		&i.ExpiresAt,
		&i.MonnifyCustomerRef,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, full_name, email, phone_number, password, is_verified, created_at, updated_at, nin, expires_at, monnify_customer_ref FROM users
WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nin,
		&i.ExpiresAt,
		&i.MonnifyCustomerRef,
	)
	return i, err
}

const getUserWithAccountsByAccountNumber = `-- name: GetUserWithAccountsByAccountNumber :many
SELECT
    u.id,
    u.password,
    u.full_name,
    u.email,
    u.phone_number,
    u.is_verified,
    a.id AS account_id,
    a.account_number,
    a.account_type,
    a.balance,
    a.currency,
    a.virtual_account_bank
FROM users u
JOIN accounts a ON a.user_id = u.id
WHERE u.id = (
    SELECT user_id
    FROM accounts as acc
    WHERE acc.account_number = $1
)
ORDER BY a.created_at
`

type GetUserWithAccountsByAccountNumberRow struct {
	ID                 uuid.UUID      `json:"id"`
	Password           string         `json:"password"`
	FullName           string         `json:"full_name"`
	Email              string         `json:"email"`
	PhoneNumber        string         `json:"phone_number"`
	IsVerified         pgtype.Bool    `json:"is_verified"`
	AccountID          uuid.UUID      `json:"account_id"`
	AccountNumber      string         `json:"account_number"`
	AccountType        string         `json:"account_type"`
	Balance            pgtype.Numeric `json:"balance"`
	Currency           string         `json:"currency"`
	VirtualAccountBank pgtype.Text    `json:"virtual_account_bank"`
}

func (q *Queries) GetUserWithAccountsByAccountNumber(ctx context.Context, accountNumber string) ([]GetUserWithAccountsByAccountNumberRow, error) {
	rows, err := q.db.Query(ctx, getUserWithAccountsByAccountNumber, accountNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWithAccountsByAccountNumberRow
	for rows.Next() {
		var i GetUserWithAccountsByAccountNumberRow
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.AccountID,
			&i.AccountNumber,
			&i.AccountType,
			&i.Balance,
			&i.Currency,
			&i.VirtualAccountBank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithAccountsByEmail = `-- name: GetUserWithAccountsByEmail :many
SELECT 
    u.id,
    u.password,
    u.full_name,
    u.email,
    u.phone_number,
    u.is_verified,
    a.account_number,
    a.account_type,
    a.balance,
    a.currency,
    a.virtual_account_bank
FROM users u
LEFT JOIN accounts a ON a.user_id = u.id
WHERE u.email = $1
`

type GetUserWithAccountsByEmailRow struct {
	ID                 uuid.UUID      `json:"id"`
	Password           string         `json:"password"`
	FullName           string         `json:"full_name"`
	Email              string         `json:"email"`
	PhoneNumber        string         `json:"phone_number"`
	IsVerified         pgtype.Bool    `json:"is_verified"`
	AccountNumber      pgtype.Text    `json:"account_number"`
	AccountType        pgtype.Text    `json:"account_type"`
	Balance            pgtype.Numeric `json:"balance"`
	Currency           pgtype.Text    `json:"currency"`
	VirtualAccountBank pgtype.Text    `json:"virtual_account_bank"`
}

func (q *Queries) GetUserWithAccountsByEmail(ctx context.Context, email string) ([]GetUserWithAccountsByEmailRow, error) {
	rows, err := q.db.Query(ctx, getUserWithAccountsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWithAccountsByEmailRow
	for rows.Next() {
		var i GetUserWithAccountsByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.AccountNumber,
			&i.AccountType,
			&i.Balance,
			&i.Currency,
			&i.VirtualAccountBank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithAccountsByUserID = `-- name: GetUserWithAccountsByUserID :many
SELECT
    u.id,
    u.password,
    u.full_name,
    u.email,
    u.phone_number,
    u.is_verified,
    a.id AS account_id,
    a.account_number,
    a.account_type,
    a.balance,
    a.currency,
    a.virtual_account_bank
FROM users u
JOIN accounts a ON a.user_id = u.id
WHERE u.id = $1
ORDER BY a.created_at
`

type GetUserWithAccountsByUserIDRow struct {
	ID                 uuid.UUID      `json:"id"`
	Password           string         `json:"password"`
	FullName           string         `json:"full_name"`
	Email              string         `json:"email"`
	PhoneNumber        string         `json:"phone_number"`
	IsVerified         pgtype.Bool    `json:"is_verified"`
	AccountID          uuid.UUID      `json:"account_id"`
	AccountNumber      string         `json:"account_number"`
	AccountType        string         `json:"account_type"`
	Balance            pgtype.Numeric `json:"balance"`
	Currency           string         `json:"currency"`
	VirtualAccountBank pgtype.Text    `json:"virtual_account_bank"`
}

func (q *Queries) GetUserWithAccountsByUserID(ctx context.Context, id uuid.UUID) ([]GetUserWithAccountsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getUserWithAccountsByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWithAccountsByUserIDRow
	for rows.Next() {
		var i GetUserWithAccountsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Password,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.IsVerified,
			&i.AccountID,
			&i.AccountNumber,
			&i.AccountType,
			&i.Balance,
			&i.Currency,
			&i.VirtualAccountBank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many


SELECT id, full_name, email, phone_number, password, is_verified, created_at, updated_at, nin, expires_at, monnify_customer_ref FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// SELECT
//     u.id,
//     u.password,
//     u.full_name,
//     u.email,
//     u.phone_number,
//     u.is_verified,
//     a.id AS account_id,
//     a.account_number,
//     a.account_type,
//     a.balance,
//     a.currency,
//     a.virtual_account_bank
// FROM accounts acc
// JOIN users u ON u.id = acc.user_id
// JOIN accounts a ON a.user_id = u.id
// WHERE acc.account_number = $1
// ORDER BY a.created_at;
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.Password,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Nin,
			&i.ExpiresAt,
			&i.MonnifyCustomerRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserFullNameAndEmail = `-- name: UpdateUserFullNameAndEmail :one
UPDATE users
SET full_name = $2, email = $3
WHERE id = $1
RETURNING id, full_name, email, phone_number, password, is_verified, created_at, updated_at, nin, expires_at, monnify_customer_ref
`

type UpdateUserFullNameAndEmailParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
}

func (q *Queries) UpdateUserFullNameAndEmail(ctx context.Context, arg UpdateUserFullNameAndEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFullNameAndEmail, arg.ID, arg.FullName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.Password,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nin,
		&i.ExpiresAt,
		&i.MonnifyCustomerRef,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID `json:"id"`
	Password string    `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users
SET is_verified = TRUE
WHERE id = $1
`

func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
