-- 1️⃣ Drop primary key
ALTER TABLE transactions
    DROP CONSTRAINT transactions_pkey;

-- 2️⃣ Drop the id column completely
ALTER TABLE transactions
    DROP COLUMN id;

-- 3️⃣ Recreate id as BIGINT identity
ALTER TABLE transactions
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
